### ISSUE TITLE
Simple test

### ISSUE THREAD

**Issue by remydev** [anykeyh/json_on_steroids#2]
Hi
Happy to see you again in a great project again after clear ;)

There isn't installation method, so i don't know if I miss something, but i have this error on your example in this repo :https://github.com/remydev/test_json_on_steroids

```
/test_json_on_steroids > crystal run src/main.cr
Showing last frame. Use --error-trace for full trace.

In src/main.cr:5:42

 5 | json = JSON.parse(%<{"a": 1, "b": 2}>).on_steroids
                                            ^----------
Error: undefined method 'on_steroids' for JSON::Any

Did you mean 'on_steroids!'?

```

**Comment by anykeyh** [comment]
Hello,

The documentation is a bit outdated, the method name is `on_steroids!`

**Comment by anykeyh** [comment]
I've updated the documentation!
